# Go Test Coverage configuration

threshold:
  # Aiming for 80%, but setting to current reality + buffer to allow CI to pass
  total: 60

# Specify packages for detailed reporting
# engine and reflectx are the most critical
report:
  # Enable reporting for these packages
  include:
    - github.com/rpadovani/sqlx-v2
    - github.com/rpadovani/sqlx-v2/internal/bind/...
    - github.com/rpadovani/sqlx-v2/internal/reflectx/...
    - github.com/rpadovani/sqlx-v2/reflectx/...
    - github.com/rpadovani/sqlx-v2/internal/mockdb

# Fail if coverage decreases
fail-on-negative-delta: true

# These are for the badge/chart generation if supported by the action
chart: true
help: true
